name: 'Merge git branches'
description:
  'Keep multiple branches up to date within your CI workflows.'
author: 'Timon Jurschitsch'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  branches:
    description:
      'The branches that need to be updated. Takes either a string or an array
      of strings.'
    required: true
  token:
    description: 'GitHub Personal Access Token needed for the commit.'
    required: true
  force:
    description:
      'Defines if the commit should be force-pushed or not. Default is false.'
    required: false
    default: 'false'
  checkTags:
    description:
      'Enable tag checks by setting checkTags to true if you want to include tag
      validation in the GitHub Action workflow. Default is false.'
    required: false
    default: 'false'

runs:
  using: node20
  main: dist/index.js
