name: Merge branches

on:
  push:
    branches:
      - main

jobs:
  merge-branches:
    name: Merge main into develop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test Local Action
        uses: ./
        with:
          token: ${{ secrets.GH_TOKEN }}
          branches: develop
          force: true
